### ISSUE TITLE
Some charset problems on Windows

### ISSUE THREAD

**Issue by adaptun** [theconst/aodbc#1]
npm test on Windows prints garbled Cyrillic symbols:

```
C:\work\aodbc-master>npm test

> cacheodbc@0.0.2 test C:\work\aodbc-master
> mocha test/**spec.js --reporter spec --full-trace --timeout 5000



ODBC Connection integration tests
1) should connect with dsn, username, password
√ should return connected for new instance
DBMS Name: InterSystems Iris
√ should display name of the dbms
DBMS version: Cache Objects Version 2017.2.2.865 Cache xDBC Server 8.01
√ should display version of the database
Driver name: IrisODBC3564.DLL
√ should display driver name
- should display catalog name
Database name: SAMPLES
√ should display dabase name
- should return disconnected after disconnect
- should reconnect after disconnect
√ should do do nothing on connection close
√ should create with default constructor and no timeout args (100ms)
√ should create with default constructor and timeout args (44ms)
Error: null
√ should execute query 1 (73ms)
Error: null
√ should execute query 2 (241ms)
Error: null
√ should execute query 3 (87ms)
Error: null
√ should execute query 4 (619ms)
Error: null
√ should execute query 5
- should execute query 6
[ { Name: 'Davis,Brian O.',
DOB: 1969-12-31T23:59:59.000Z,
Spouse: 51 },
{ Name: 'Davis,Dave Z.',
DOB: 1970-01-11T09:24:22.784Z,
Spouse: 29 },
{ Name: 'DeLillo,Xavier U.',
DOB: 1969-12-31T23:59:59.000Z,
Spouse: null },
{ Name: 'Drabek,Alexandra O.',
DOB: 1969-12-31T23:59:59.000Z,
Spouse: 19 },
{ Name: 'Dunlap,Jane A.',
DOB: 1969-12-31T23:59:59.000Z,
Spouse: 84 },
{ Name: 'Dunlap,Mark J.',
DOB: 1969-12-31T23:59:59.000Z,
Spouse: 6 },
{ Name: 'Dunlap,Pam U.',
DOB: 1969-12-29T00:13:19.872Z,
Spouse: null } ]
√ should call stored procedure (196ms)

ODBC Statement integration tests
√ should create prepared statement
√ should execute prepared statement with no args 1
√ should execute prepared statement with no args 2
[ { Q: '1' } ]
[ { Q: '2' } ]
√ should execute prepared statement twice 1
[ { ID: 111, Name: 'MacroSoft Corp.' },
{ ID: 129, Name: 'MacroSoft Corp.' },
{ ID: 198, Name: 'MacroSoft Corp.' },
{ ID: 149, Name: 'MetaData Partners' },
{ ID: 116, Name: 'MetaPedia Partners' },
{ ID: 154, Name: 'MetaTel Corp.' },
{ ID: 187, Name: 'OptiData Holdings Inc.' },
{ ID: 141, Name: 'OptiSystems Holdings Inc.' },
{ ID: 115, Name: 'TeraDynamics Associates' },
{ ID: 136, Name: 'YoyoTel LLC.' } ]
[ { ID: 110, Name: 'MacroSoft Corp.' },
{ ID: 111, Name: 'MacroSoft Corp.' },
{ ID: 125, Name: 'MacroSoft Corp.' },
{ ID: 129, Name: 'MacroSoft Corp.' },
{ ID: 198, Name: 'MacroSoft Corp.' },
{ ID: 149, Name: 'MetaData Partners' },
{ ID: 116, Name: 'MetaPedia Partners' },
{ ID: 112, Name: 'MetaSoft Group Ltd.' },
{ ID: 122, Name: 'MetaSoft Group Ltd.' },
{ ID: 154, Name: 'MetaTel Corp.' },
{ ID: 187, Name: 'OptiData Holdings Inc.' },
{ ID: 141, Name: 'OptiSystems Holdings Inc.' },
{ ID: 191, Name: 'QuantaGlomerate Corp.' },
{ ID: 115, Name: 'TeraDynamics Associates' },
{ ID: 136, Name: 'YoyoTel LLC.' } ]
√ should execute prepared statement twice 2 (75ms)
[ { ID: 111, Name: 'MacroSoft Corp.' },
{ ID: 129, Name: 'MacroSoft Corp.' },
{ ID: 198, Name: 'MacroSoft Corp.' },
{ ID: 149, Name: 'MetaData Partners' },
{ ID: 116, Name: 'MetaPedia Partners' },
{ ID: 154, Name: 'MetaTel Corp.' },
{ ID: 187, Name: 'OptiData Holdings Inc.' },
{ ID: 141, Name: 'OptiSystems Holdings Inc.' },
{ ID: 115, Name: 'TeraDynamics Associates' },
{ ID: 136, Name: 'YoyoTel LLC.' } ]
√ should execute no args prepared statement
[Error: c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1843: ]
√ should close statment and not query thereafter

ODBC Transaction integration tests
√ should create transaction
√ should commit transation (91ms)
√ should rollback transation (101ms)

BIGINT spec
[2018-11-23T12:49:27.514Z] [{"id":"M13","val":"8191"},{"id":"M17","val":"131071"},{"id":"M31","val":"2147483647"},{"id":"ZMAX","val":"9223372036854775807"},{"id":"ZMINA","val":"-999999999999999999"},{"id":"ZZZZ","val":null}]
√ should convert big integer datatype (48ms)

BINARY spec
√ should convert binary datatype (39ms)

BIT spec
√ should convert bit datatype

should convert VARCHAR(15) datatype
√ should successfully convert values
√ should not fail if value is not in range

should convert CHARACTER VARYING(15) datatype
[2018-11-23T12:49:28.376Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]
√ should successfully convert values
√ should not fail if value is not in range
[2018-11-23T12:49:28.622Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

should convert CHAR VARYING(15) datatype
√ should successfully convert values
√ should not fail if value is not in range
[2018-11-23T12:49:28.896Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

should convert CHARACTER(15) datatype
√ should successfully convert values
√ should not fail if value is not in range
[2018-11-23T12:49:29.166Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

should convert CHAR(15) datatype
√ should successfully convert values
√ should not fail if value is not in range
[2018-11-23T12:49:29.447Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

should convert LONG VARCHAR(15) datatype
2) should successfully convert values
√ should not fail if value is not in range
[2018-11-23T12:49:29.744Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

should convert LONGVARCHAR(15) datatype
3) should successfully convert values
√ should not fail if value is not in range
[2018-11-23T12:49:30.021Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

should convert date and time
4) should convert dates and times datatype

should convert integers
√ should convert integers in range (43ms)
√ should fail to convert integers not in range


41 passing (7s)
4 pending
4 failing

1) ODBC Connection integration tests
should connect with dsn, username, password:
Uncaught AssertionError: expected [Error: c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:996: 0100: [Iris ODBC][State : HY000][Native Code 417]
[C:\Program Files\nodejs\node.exe]
�������� � ������� [Microsoft][ODBC Driver Manager] The driver doesn't support the version of ODBC behavior that the application requested (see SQLSetEnvAttr). ] to be null
at nc.ODBCConnection.connect.err (C:\work\aodbc-master\test\connection.integration.spec.js:25:30)

2) should convert LONG VARCHAR(15) datatype
should successfully convert values:

AssertionError: expected [ Array(4) ] to deeply equal [ Array(4) ]
+ expected - actual

[
{
- "info": "\u0003\u00011\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable0S"
+ "info": "First party"
"name": "Alice"
}
{
"info": ""
"name": "Bob"
}
{
- "info": "\u0003\u00013\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable0S"
+ "info": "Eavesdropper"
"name": "Eve"
}
{
- "info": "\u0003\u00012\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable0S"
+ "info": "Man in the"
"name": "Mallory"
}
]

at Promise.all.then.then.queryResult (C:\work\aodbc-master\test\types.integration.spec.js:302:45)
at tryCatcher (C:\work\aodbc-master\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:614:10)
at Promise._settlePromises (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:694:18)
at Promise._fulfill (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:638:18)
at C:\work\aodbc-master\node_modules\bluebird\js\release\nodeback.js:42:21

3) should convert LONGVARCHAR(15) datatype
should successfully convert values:

AssertionError: expected [ Array(4) ] to deeply equal [ Array(4) ]
+ expected - actual

[
{
- "info": "\u0003\u00011\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable1S"
+ "info": "First party"
"name": "Alice"
}
{
"info": ""
"name": "Bob"
}
{
- "info": "\u0003\u00013\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable1S"
+ "info": "Eavesdropper"
"name": "Eve"
}
{
- "info": "\u0003\u00012\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable1S"
+ "info": "Man in the"
"name": "Mallory"
}
]

at Promise.all.then.then.queryResult (C:\work\aodbc-master\test\types.integration.spec.js:302:45)
at tryCatcher (C:\work\aodbc-master\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:614:10)
at Promise._settlePromises (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:694:18)
at Promise._fulfill (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:638:18)
at C:\work\aodbc-master\node_modules\bluebird\js\release\nodeback.js:42:21

4) should convert date and time
should convert dates and times datatype:

AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
+ expected - actual

[
{
- "birthday": [Date: 1969-12-17T04:26:57.536Z]
- "last_visit": [Date: 1970-01-18T11:31:17.888Z]
- "last_visit2": [Date: 1970-01-19T08:31:17.888Z]
+ "birthday": [Date: 1995-01-01T21:00:00.000Z]
+ "last_visit": [Date: 2003-08-31T21:00:00.000Z]
+ "last_visit2": [Date: 2003-09-01T18:00:00.000Z]
"name": "Alice"
}
]

at Promise.all.then.then.queryResult (C:\work\aodbc-master\test\types.integration.spec.js:376:41)
at tryCatcher (C:\work\aodbc-master\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:614:10)
at Promise._settlePromises (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:694:18)
at Promise._fulfill (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:638:18)
at C:\work\aodbc-master\node_modules\bluebird\js\release\nodeback.js:42:21

npm ERR! Test failed. See above for more details
```

**Comment by theconst** [comment]
Hi, the problem is that you are currently trying to use Unicode enabled driver.
The support is intentionally disabled for the first release (this will cause issues for people trying to use unixodbc + cache driver on Linux and MacOS). 
I probably will need some help on correctly setting up ODBC via iODBC driver manager. I was blocked by the issue https://github.com/nanodbc/nanodbc/issues/99. I will submit PR to guys as soon as I figure out how to fix it.
Please download artifacts from https://github.com/theconst/aodbc/releases/tag/release-0.0.3 and copy them to /build/Release/ folder inside the project folder and rerun the tests again (you may copy only windows release files).

**Comment by adaptun** [comment]
I've downloaded https://github.com/theconst/aodbc/releases/download/release-0.0.3/cacheodbc-Windows-x64-v10.node

Results:

```
C:\work\aodbc-master>npm test

> cacheodbc@0.0.2 test C:\work\aodbc-master
> mocha test/**spec.js --reporter spec --full-trace --timeout 5000



  ODBC Connection integration tests
    1) should connect with dsn, username, password
    √ should return connected for new instance
DBMS Name: InterSystems Iris
    √ should display name of the dbms
DBMS version: Cache Objects Version 2017.2.2.865 Cache xDBC Server 8.01
    √ should display version of the database
Driver name: IrisODBC3564.DLL
    √ should display driver name
    - should display catalog name
Database name: SAMPLES
    √ should display dabase name
    - should return disconnected after disconnect
    - should reconnect after disconnect
    √ should do do nothing on connection close
    √ should create with default constructor and no timeout args (43ms)
    √ should create with default constructor and timeout args (49ms)
Error: null
    √ should execute query 1
Error: null
    √ should execute query 2 (65ms)
Error: null
    √ should execute query 3 (73ms)
Error: null
    √ should execute query 4 (644ms)
Error: null
    √ should execute query 5
    - should execute query 6
[ { Name: 'Davis,Brian O.',
    DOB: 1969-12-31T23:59:59.000Z,
    Spouse: 51 },
  { Name: 'Davis,Dave Z.',
    DOB: 1970-01-11T09:24:22.784Z,
    Spouse: 29 },
  { Name: 'DeLillo,Xavier U.',
    DOB: 1969-12-31T23:59:59.000Z,
    Spouse: null },
  { Name: 'Drabek,Alexandra O.',
    DOB: 1969-12-31T23:59:59.000Z,
    Spouse: 19 },
  { Name: 'Dunlap,Jane A.',
    DOB: 1969-12-31T23:59:59.000Z,
    Spouse: 84 },
  { Name: 'Dunlap,Mark J.',
    DOB: 1969-12-31T23:59:59.000Z,
    Spouse: 6 },
  { Name: 'Dunlap,Pam U.',
    DOB: 1969-12-29T00:13:19.872Z,
    Spouse: null } ]
    √ should call stored procedure

  ODBC Statement integration tests
    √ should create prepared statement
    √ should execute prepared statement with no args 1
    √ should execute prepared statement with no args 2
[ { Q: '1' } ]
[ { Q: '2' } ]
    √ should execute prepared statement twice 1
[ { ID: 111, Name: 'MacroSoft Corp.' },
  { ID: 129, Name: 'MacroSoft Corp.' },
  { ID: 198, Name: 'MacroSoft Corp.' },
  { ID: 149, Name: 'MetaData Partners' },
  { ID: 116, Name: 'MetaPedia Partners' },
  { ID: 154, Name: 'MetaTel Corp.' },
  { ID: 187, Name: 'OptiData Holdings Inc.' },
  { ID: 141, Name: 'OptiSystems Holdings Inc.' },
  { ID: 115, Name: 'TeraDynamics Associates' },
  { ID: 136, Name: 'YoyoTel LLC.' } ]
[ { ID: 110, Name: 'MacroSoft Corp.' },
  { ID: 111, Name: 'MacroSoft Corp.' },
  { ID: 125, Name: 'MacroSoft Corp.' },
  { ID: 129, Name: 'MacroSoft Corp.' },
  { ID: 198, Name: 'MacroSoft Corp.' },
  { ID: 149, Name: 'MetaData Partners' },
  { ID: 116, Name: 'MetaPedia Partners' },
  { ID: 112, Name: 'MetaSoft Group Ltd.' },
  { ID: 122, Name: 'MetaSoft Group Ltd.' },
  { ID: 154, Name: 'MetaTel Corp.' },
  { ID: 187, Name: 'OptiData Holdings Inc.' },
  { ID: 141, Name: 'OptiSystems Holdings Inc.' },
  { ID: 191, Name: 'QuantaGlomerate Corp.' },
  { ID: 115, Name: 'TeraDynamics Associates' },
  { ID: 136, Name: 'YoyoTel LLC.' } ]
    √ should execute prepared statement twice 2 (56ms)
[ { ID: 111, Name: 'MacroSoft Corp.' },
  { ID: 129, Name: 'MacroSoft Corp.' },
  { ID: 198, Name: 'MacroSoft Corp.' },
  { ID: 149, Name: 'MetaData Partners' },
  { ID: 116, Name: 'MetaPedia Partners' },
  { ID: 154, Name: 'MetaTel Corp.' },
  { ID: 187, Name: 'OptiData Holdings Inc.' },
  { ID: 141, Name: 'OptiSystems Holdings Inc.' },
  { ID: 115, Name: 'TeraDynamics Associates' },
  { ID: 136, Name: 'YoyoTel LLC.' } ]
    √ should execute no args prepared statement
[Error: c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1843: ]
    √ should close statment and not query thereafter

  ODBC Transaction integration tests
    √ should create transaction
    √ should commit transation (76ms)
    √ should rollback transation (75ms)

  BIGINT spec
[2018-11-23T15:46:06.067Z] [{"id":"M13","val":"8191"},{"id":"M17","val":"131071"},{"id":"M31","val":"2147483647"},{"id":"ZMAX","val":"9223372036854775807"},{"id":"ZMINA","val":"-999999999999999999"},{"id":"ZZZZ","val":null}]
    √ should convert big integer datatype (47ms)

  BINARY spec
    √ should convert binary datatype

  BIT spec
    √ should convert bit datatype

  should convert VARCHAR(15) datatype
    √ should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:06.859Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert CHARACTER VARYING(15) datatype
    √ should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:07.127Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert CHAR VARYING(15) datatype
    √ should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:07.371Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert CHARACTER(15) datatype
    √ should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:07.631Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert CHAR(15) datatype
    √ should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:07.878Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert LONG VARCHAR(15) datatype
    2) should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:08.147Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert LONGVARCHAR(15) datatype
    3) should successfully convert values
    √ should not fail if value is not in range
[2018-11-23T15:46:08.468Z] c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:1626: 4200: [Iris ODBC][State : 42000][Native Code 1]
[C:\Program Files\nodejs\node.exe]
[SQLCODE: <-1>:<������������ SQL-��������>]
[Location: <Prepare>]
[%msg: < ��������� SELECT, ���������� ������������� (name)^INSERT INTO ( name>]

  should convert date and time
    4) should convert dates and times datatype

  should convert integers
    √ should convert integers in range (53ms)
    √ should fail to convert integers not in range


  41 passing (6s)
  4 pending
  4 failing

  1) ODBC Connection integration tests
       should connect with dsn, username, password:
     Uncaught AssertionError: expected [Error: c:\users\travis\build\theconst\aodbc\nanodbc\nanodbc\nanodbc.cpp:996: 0100: [Iris ODBC][State : HY000][Native Code 417]
[C:\Program Files\nodejs\node.exe]
�������� � �������  [Microsoft][ODBC Driver Manager] The driver doesn't support the version of ODBC behavior that the application requested (see SQLSetEnvAttr). ] to be null
      at nc.ODBCConnection.connect.err (C:\work\aodbc-master\test\connection.integration.spec.js:25:30)

  2) should convert LONG VARCHAR(15) datatype
       should successfully convert values:

      AssertionError: expected [ Array(4) ] to deeply equal [ Array(4) ]
      + expected - actual

       [
         {
      -    "info": "\u0004\u000110\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable0S"
      +    "info": "First party"
           "name": "Alice"
         }
         {
           "info": ""
           "name": "Bob"
         }
         {
      -    "info": "\u0004\u000112\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable0S"
      +    "info": "Eavesdropper"
           "name": "Eve"
         }
         {
      -    "info": "\u0004\u000111\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable0S"
      +    "info": "Man in the"
           "name": "Mallory"
         }
       ]

      at Promise.all.then.then.queryResult (C:\work\aodbc-master\test\types.integration.spec.js:302:45)
      at tryCatcher (C:\work\aodbc-master\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:512:31)
      at Promise._settlePromise (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:569:18)
      at Promise._settlePromise0 (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:614:10)
      at Promise._settlePromises (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:694:18)
      at Promise._fulfill (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:638:18)
      at C:\work\aodbc-master\node_modules\bluebird\js\release\nodeback.js:42:21

  3) should convert LONGVARCHAR(15) datatype
       should successfully convert values:

      AssertionError: expected [ Array(4) ] to deeply equal [ Array(4) ]
      + expected - actual

       [
         {
      -    "info": "\u0004\u000110\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable1S"
      +    "info": "First party"
           "name": "Alice"
         }
         {
           "info": ""
           "name": "Bob"
         }
         {
      -    "info": "\u0004\u000112\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable1S"
      +    "info": "Eavesdropper"
           "name": "Eve"
         }
         {
      -    "info": "\u0004\u000111\u0019\u0001%Stream.GlobalCharacter\u001e\u0001^Sample.CharacterTestTable1S"
      +    "info": "Man in the"
           "name": "Mallory"
         }
       ]

      at Promise.all.then.then.queryResult (C:\work\aodbc-master\test\types.integration.spec.js:302:45)
      at tryCatcher (C:\work\aodbc-master\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:512:31)
      at Promise._settlePromise (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:569:18)
      at Promise._settlePromise0 (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:614:10)
      at Promise._settlePromises (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:694:18)
      at Promise._fulfill (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:638:18)
      at C:\work\aodbc-master\node_modules\bluebird\js\release\nodeback.js:42:21

  4) should convert date and time
       should convert dates and times datatype:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual

       [
         {
      -    "birthday": [Date: 1969-12-17T04:26:57.536Z]
      -    "last_visit": [Date: 1970-01-18T11:31:17.888Z]
      -    "last_visit2": [Date: 1970-01-19T08:31:17.888Z]
      +    "birthday": [Date: 1995-01-01T21:00:00.000Z]
      +    "last_visit": [Date: 2003-08-31T21:00:00.000Z]
      +    "last_visit2": [Date: 2003-09-01T18:00:00.000Z]
           "name": "Alice"
         }
       ]

      at Promise.all.then.then.queryResult (C:\work\aodbc-master\test\types.integration.spec.js:376:41)
      at tryCatcher (C:\work\aodbc-master\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:512:31)
      at Promise._settlePromise (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:569:18)
      at Promise._settlePromise0 (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:614:10)
      at Promise._settlePromises (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:694:18)
      at Promise._fulfill (C:\work\aodbc-master\node_modules\bluebird\js\release\promise.js:638:18)
      at C:\work\aodbc-master\node_modules\bluebird\js\release\nodeback.js:42:21



npm ERR! Test failed.  See above for more details.
```

**Comment by theconst** [comment]
Temporary workaround:
1. Use Cache ODBC driver, as in instruction.
2. Use english locale.

With logs - I can decode them before logging.
Regarding IrisODBC where can I get it?
Thanks

**Comment by theconst** [comment]
Looks like IrisODBC is using streams for longvarchar. CacheODBC driver used strings (or I have an older version of Cache): 
https://github.com/theconst/aodbc/blob/master/src/fetch.cc.
I will create an MR for fixing this soon (your PRs are also welcoem).

**Comment by theconst** [comment]
https://github.com/theconst/aodbc/releases/tag/release-0.0.4. Now test should fail because of binary type returned.
Regarding dates... I still cannot find out the reason

**Comment by theconst** [comment]
I will split this one into two:
1. Incorrect unicde support
2. Incorrect dates handling on Windows (I did not notice the failure with dates on Windows, because was running my tests on a Linux machine).
3. Incorrect encoding of errors on Windows (in unixodbc I was able to see Russian error messages from driver manager).

**Comment by theconst** [comment]
https://github.com/theconst/aodbc/pull/8
